# Generated by Django 3.2.15 on 2022-10-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aquainfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('days', models.IntegerField()),
                ('num', models.IntegerField()),
                ('average_weight', models.FloatField()),
                ('total_weight', models.FloatField()),
                ('biomass', models.FloatField()),
                ('survival_rate', models.FloatField()),
                ('feed', models.FloatField()),
                ('weekly_growth_rate', models.FloatField()),
                ('total_weight_increase', models.FloatField()),
                ('feed_conversion_rate', models.FloatField()),
                ('remarks', models.TextField()),
            ],
        ),
    ]
